apiVersion: apps/v1
kind: Deployment
metadata:
  name : echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  replicas: 2
  template: 
    metadata:
      labels: 
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: k8s.gcr.io/echoserver:1.4
